version: '3.5'

services:
  symfony-shortened-web:
    container_name: symfony-shortened-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 8000:80
    volumes:
      - ./backend/public:/appdata/www/public
    networks:
      - symfony-shortened-network
    depends_on:
      - symfony-shortened-backend
      - symfony-shortened-frontend

  symfony-shortened-backend:
    container_name: symfony-shortened-backend
    build:
      context: ./docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005
    volumes:
      - ./backend:/appdata/www
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    networks:
      - symfony-shortened-network
    depends_on:
      - symfony-shortened-db

  symfony-shortened-db:
    container_name: symfony-shortened-db
    image: mysql:8.0
    ports:
      - 40000:3306
    env_file:
      - ${PWD}/docker.env
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - symfony-shortened-database-data:/var/lib/mysql
    networks:
      - symfony-shortened-network

  symfony-shortened-frontend:
    container_name: symfony-shortened-frontend
    build:
      context: ./frontend
      target: 'build-stage'
      args:
        UID: $U_ID
    tty: true
    ports:
    - 8080:8080
    volumes:
    - ./frontend:/frontend
    command: /bin/sh -c "npm run serve"
    networks:
      - symfony-shortened-network

volumes:
  symfony-shortened-database-data:

networks:
  symfony-shortened-network:
    external: true